server:
  port: 10010
spring:
  redis: #redis配置
    database: 0
    host: "localhost"
    port: 6379
    password: "1819891412"
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    token: #token超时时间
      expiration-time: 1800
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service #路由标识，必须唯一
          uri: lb://user-service #路由的目标地址
          predicates: #路由断言，判断请求是否符合规则
            - Path=/user/** #路由断言，判断路径是否以/user开头，如果是则符合
        - id: article-service #路由标识，必须唯一
          uri: lb://article-service #路由的目标地址
          predicates: #路由断言，判断请求是否符合规则
            - Path=/article/** #路由断言，判断路径是否以/user开头，如果是则符合
        - id: img-service #路由标识，必须唯一
          uri: lb://img-service #路由的目标地址
          predicates: #路由断言，判断请求是否符合规则
            - Path=/img/** #路由断言，判断路径是否以/user开头，如果是则符合
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" #允许哪些网站的跨域请求
            allowedMethods: #允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带cookie
            allowCredentials: true #是否允许携带cookie
            maxAge: 360000 #这次跨域检测的有效期
