server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/article-service?serverTimezone=GMT%2b8&useSSL=false&characterEncoding=UTF-8
    username: root
    password: "root"
  cloud:
    nacos:
      server-addr: localhost:8848
  application:
    name: article-service
feign:
  httpclient:
    enabled: true #支持httpclient的开关
    max-connections: 200 #最大连接数
    max-connections-per-route: 50 #单个路径最大连接数
