server:
  port: 8086
  location: "125.88.217.207"
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://125.88.217.207:3306/article-service?serverTimezone=GMT%2b8&useSSL=false&characterEncoding=UTF-8
    username: es-service
    password: "1819891412s"
    hikari:
      connection-timeout: 1000
  cloud:
    nacos:
      server-addr: localhost:8848
  application:
    name: article-service
  rabbitmq:
    host: 125.88.217.207
    port: 5672
    username: root
    password: 1819891412
    virtual-host: /

feign:
  httpclient:
    enabled: true #支持httpclient的开关
    max-connections: 200 #最大连接数
    max-connections-per-route: 50 #单个路径最大连接数
elasticsearch:
  host: "${server.location}"
  port: "9200"
  connTimeout: 3000
  socketTimeout: 5000
  connectionRequestTimeout: 500
